apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "car-database.fullname" . }}-config
  labels:
    app: {{ template "car-database.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  properties.properties: |-
{{ toYaml .Values.properties | indent 4 }}
